### ISSUE TITLE
Unable to build on Ubuntu 21.10

### ISSUE THREAD

**Issue by janstarke** [sunsetkookaburra/rust-libesedb#1]
Hi,

trying to build your lib (using `cargo build`, I get the attached error message:

[build.log](https://github.com/sunsetkookaburra/rust-libesedb/files/9043926/build.log)

Could you please take a look at what might be wrong?

Regards, Jan

**Comment by sunsetkookaburra** [comment]
Hello,

I had the same issue pop up when docs.rs tried to build the project, but for that I just stopped it from compiling on docs.rs.

Thanks very much for your pull request, at a quick glance I'm pretty sure it'll fix the problem. Of course it would be tidier if all of the `c.define`s weren't needed, but if it works to solve the problem that's terrific.

Right now I'll get an Action setup to build and test on the repository itself and reproduce the issue, and it should also run your patch.

Many thanks, Oli

**Comment by sunsetkookaburra** [comment]
Got the issue to be reproduced: https://github.com/sunsetkookaburra/rust-libesedb/runs/7244410738
