### ISSUE TITLE
Bump `libesedb-sys` to latest version

### ISSUE THREAD

**Issue by alexkornitzer** [sunsetkookaburra/rust-libesedb#13]
Hey,

Please could you bump `libesedb-sys` to the latest upstream version so that it successfully compiles on macOS? For context, this is blocking @catarinadf from getting some new features into Chainsaw. Happy to assist if you are strapped for time.

Thanks in advance,

Alex

**Comment by sunsetkookaburra** [comment]
Hello,

I've put together something from the upstream libesedb at version 20230824 in a branch, though I'm having a couple difficulties with includes/headers at the moment. 

First step will be to make sure the normal Windows/Ubuntu GitHub Actions are working. After that, I don't have macOS personally to test it, but it looks like Actions supports macOS now so I'll give that a go.

I should have time over the next couple days to work on this. If it takes longer, your help would be really appreciated, but I'll let you know here.

Thanks,
\- Oli

**Comment by sunsetkookaburra** [comment]
Hi @alexkornitzer,

I've pushed some changes to main in 86c3347785b2059dfd5c48d5229f33556126d8cb that at least pass compilation on a `macos-latest` action (https://github.com/sunsetkookaburra/rust-libesedb/actions/runs/6359596165).

Are you or @catarinadf able to verify locally that it compiles for macOS now?
If it works I'll go ahead and update the crate.

**Comment by alexkornitzer** [comment]
Hi @sunsetkookaburra, thank you for actioning this so quickly, I really appreciate it. Have just tested it and its working on macOS for me.

**Comment by sunsetkookaburra** [comment]
Awesome. Just published to crates.io updating both libesedb and the libesedb-sys crates.
This ended up being a good opportunity to rework the build script a little bit to use `configure` on Unix systems too.

Thanks for the submission, and best of luck. Hopefully you find the crate useful.
\- Oli

(Closed by eced3f2c13c4628cdc5cf70b2f5221e127cf5c51)
