### ISSUE TITLE
Error: rust-libesedb: Unexpected error when calling C function `libesedb_record_get_value_32bit`

### ISSUE THREAD

**Issue by janstarke** [sunsetkookaburra/rust-libesedb#14]
The same problem applies to other C functions as well. The reason seems to be that `libesedb_record_get_value_32bit` returns `0` if the field contains no value, but `Value::load` handles all return values different from `1` as error:

https://github.com/sunsetkookaburra/rust-libesedb/blob/eced3f2c13c4628cdc5cf70b2f5221e127cf5c51/src/value.rs#L276-L287

You can find the testdata that I'm used in <https://github.com/janstarke/ntdsextract2/blob/10-include-deleted-entries-in-timeline/tests/data/ntds_plain.dit>. I created this file from scratch without private data, so you can copy it and use it for testing.

Regards, Jan

**Comment by sunsetkookaburra** [comment]
Hi @janstarke,

I've done a little refactoring and should hopefully have fixed the problem, let me know how it goes then I can bump/release for crates.io.

I've had a go at testing with your data file, and have now hit a libesedb_record_get_value_32bit error that I'm assuming is associated with long/multi-values (which aren't currently mapped in the bindings). I'll take a look at that over the coming days.
```
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "c-libesedb: libesedb_record_get_value_32bit: unable to copy value to 32-bit value.\nlibfvalue_integer_copy_from_byte_stream: unsupported byte stream size: 120.\nlibfvalue_value_get_value_instance_by_index: unable to copy value instance from byte stream.\nlibfvalue_value_copy_to_32bit: unable to retrieve value instance: 0.\nlibesedb_record_get_value_32bit: unable to copy value to 32-bit value." }
```

\- Oli

**Comment by sunsetkookaburra** [comment]
Long / Multi-values supported too, and updated package released on crates.io

**Comment by janstarke** [comment]
Works like a charm, Thank you very much! Will be part of ntdsextract 1.0 (which is nearly final)
